import { Resend } from 'resend';

// Initialize Resend safely - avoid crashing if API key is missing during build
const resend = new Resend(process.env.RESEND_API_KEY || 're_dummy_key');
const FROM_EMAIL = process.env.RESEND_FROM_EMAIL || 'security@phish-slayer.com';

/**
 * Sends a critical threat alert email to configured SOC analysts/managers.
 */
export async function sendCriticalThreatAlert(params: {
  target: string;
  threatCategory: string;
  riskScore: number;
  aiSummary: string;
  recipients: string[];
}) {
  if (!process.env.RESEND_API_KEY || params.recipients.length === 0) return { success: true };

  try {
    const { data, error } = await resend.emails.send({
      from: `Phish-Slayer Alerts <${FROM_EMAIL}>`,
      to: params.recipients,
      subject: `🚨 CRITICAL THREAT DETECTED: ${params.target}`,
      html: `
        <div style="font-family: sans-serif; max-w: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 8px; padding: 24px;">
          <h2 style="color: #dc2626; margin-top: 0;">Critical Threat Detected</h2>
          <p><strong>Target:</strong> <code style="background: #f1f5f9; padding: 2px 6px; border-radius: 4px;">${params.target}</code></p>
          <p><strong>Category:</strong> ${params.threatCategory}</p>
          <p><strong>Risk Score:</strong> <span style="color: #dc2626; font-weight: bold;">${params.riskScore}/100</span></p>
          
          <div style="background: #f8fafc; border-left: 4px solid #3b82f6; padding: 16px; margin-top: 24px;">
            <h4 style="margin-top: 0; color: #1e293b;">AI Summary</h4>
            <p style="color: #475569; margin-bottom: 0;">${params.aiSummary}</p>
          </div>
          
          <p style="margin-top: 32px; font-size: 12px; color: #94a3b8;">
            This is an automated alert generated by the Phish-Slayer Command Center.
          </p>
        </div>
      `,
    });

    if (error) console.error('[Resend] Critical Alert Error:', error);
    return { data, error };
  } catch (err) {
    console.error('[Resend] Unexpected error:', err);
    return { error: 'Failed to send critical threat alert' };
  }
}

/**
 * Sends an email notification when an incident is assigned to a user.
 */
export async function sendIncidentAssignmentEmail(params: {
  incidentId: string;
  incidentTitle: string;
  assignerName: string;
  recipientEmail: string;
}) {
  if (!process.env.RESEND_API_KEY) return { success: true };

  try {
    const { data, error } = await resend.emails.send({
      from: `Phish-Slayer Notifications <${FROM_EMAIL}>`,
      to: params.recipientEmail,
      subject: `📋 Incident Assigned to You: ${params.incidentTitle}`,
      html: `
        <div style="font-family: sans-serif; max-w: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 8px; padding: 24px;">
          <h2 style="color: #0f172a; margin-top: 0;">New Incident Assignment</h2>
          <p>Hello,</p>
          <p><strong>${params.assignerName}</strong> has assigned an incident to you.</p>
          
          <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 16px; margin: 24px 0;">
            <p style="margin: 0;"><strong>Incident ID:</strong> ${params.incidentId}</p>
            <p style="margin: 8px 0 0 0;"><strong>Title:</strong> ${params.incidentTitle}</p>
          </div>
          
          <a href="${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'}/dashboard/incidents" 
             style="display: inline-block; background: #0f172a; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold;">
            View Incident
          </a>
          
          <p style="margin-top: 32px; font-size: 12px; color: #94a3b8;">
            You are receiving this email because of your notification preferences in Phish-Slayer.
          </p>
        </div>
      `,
    });

    if (error) console.error('[Resend] Assignment Email Error:', error);
    return { data, error };
  } catch (err) {
    console.error('[Resend] Unexpected error:', err);
    return { error: 'Failed to send assignment alert' };
  }
}

/**
 * Sends a weekly digest report of scan metrics and active incidents.
 */
export async function sendWeeklyDigest(params: {
  totalScans: number;
  maliciousFound: number;
  openIncidents: number;
  recipients: string[];
}) {
  if (!process.env.RESEND_API_KEY || params.recipients.length === 0) return { success: true };

  try {
    const { data, error } = await resend.emails.send({
      from: `Phish-Slayer Reports <${FROM_EMAIL}>`,
      to: params.recipients,
      subject: `📊 Phish-Slayer Weekly Digest`,
      html: `
        <div style="font-family: sans-serif; max-w: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 8px; padding: 24px;">
          <h2 style="color: #0d9488; margin-top: 0;">Weekly Security Digest</h2>
          <p>Here is a summary of the activity over the last 7 days.</p>
          
          <table style="width: 100%; border-collapse: collapse; margin-top: 24px;">
            <tr>
              <td style="padding: 12px; border-bottom: 1px solid #f1f5f9; color: #475569;">Total Scans Performed</td>
              <td style="padding: 12px; border-bottom: 1px solid #f1f5f9; text-align: right; font-weight: bold; font-size: 18px;">${params.totalScans}</td>
            </tr>
            <tr>
              <td style="padding: 12px; border-bottom: 1px solid #f1f5f9; color: #475569;">Malicious Threats Blocked</td>
              <td style="padding: 12px; border-bottom: 1px solid #f1f5f9; text-align: right; font-weight: bold; font-size: 18px; color: #dc2626;">${params.maliciousFound}</td>
            </tr>
            <tr>
              <td style="padding: 12px; color: #475569;">Open Incidents</td>
              <td style="padding: 12px; text-align: right; font-weight: bold; font-size: 18px; color: #ca8a04;">${params.openIncidents}</td>
            </tr>
          </table>
          
          <p style="margin-top: 32px; font-size: 12px; color: #94a3b8; text-align: center;">
            Phish-Slayer Engine • Automated Reporting
          </p>
        </div>
      `,
    });

    if (error) console.error('[Resend] Weekly Digest Error:', error);
    return { data, error };
  } catch (err) {
    console.error('[Resend] Unexpected error:', err);
    return { error: 'Failed to send weekly digest' };
  }
}
